name: Check code style with Ruff
on:
  pull_request:
jobs:
  check_code_style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      # Update output format to enable automatic inline annotations.
      - name: Check style with Ruff
        run: uv run ruff check --output-format=github .
