name: Check code style with Ruff
on:
  pull_request:
jobs:
  check_code_style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        # with:
          # python-version: "3.11"
          # Should read this from .python-version.

      - name: Install uv
        run: pip install uv

      # Update output format to enable automatic inline annotations.
      - name: Check style with Ruff
        run: uv run ruff check --output-format=github .
