name: Run tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # python-version: "3.12"   # match your project's Python version
          # setup-python should pick up the version from .python-version.

      - name: Install uv
        run: pip install uv

      - name: Run tests with pytest
        run: uv run pytest
